### ISSUE TITLE
"Uncaught TypeError: n.detail is null" when clicking link

### ISSUE THREAD

**Issue by TimVanHerwijnen** [inertiajs/progress#10]
Hello,

I added this to my Laravel Jetstream Inertia project:
```
// Loading indicator
import { InertiaProgress } from '@inertiajs/progress'
InertiaProgress.init()
```
### The issue
Every time I click an inertia link i get this error:

![Screenshot_117](https://user-images.githubusercontent.com/60601502/99533117-a89aec00-29a5-11eb-9968-bc6543d3bd19.png)

### Expected behavior
The bar starts loading when clicking a link and finish once the page is loaded.

### Actual behavior 
Throws an error and the progress bar just continues to load until about 98% while the page has already been loaded.

**Comment by shahirWebo** [comment]
I am also facing same issue. The issue is InertiaProgress is required new version of Inertia js. when we use old version the error will occurring

**Comment by reinink** [comment]
Yeah, making sure you're using the right versions, as per the peer dependencies.

**Comment by TimVanHerwijnen** [comment]
Updating the packages solved the problem. Thank you!
I am now finally able to see the beauty of this package! :)

**Comment by reinink** [comment]
@TimVanHerwijnen Excellent! 🙌

**Comment by silasrm** [comment]
> Updating the packages solved the problem. Thank you!
> I am now finally able to see the beauty of this package! :)

Please, tell me how you solve (packages versions) :D
I'm using with Jetstream this versions, but don't solve:

_package.json_
```
        "@inertiajs/inertia": "^0.3.6",
        "@inertiajs/inertia-vue": "^0.2.4",
        "@inertiajs/progress": "^0.2.3",
```

_composer.json_
```
        "inertiajs/inertia-laravel": "^0.3.4",
```
