### ISSUE TITLE
Allow configuration of parent container

### ISSUE THREAD

**Issue by crispincornett** [inertiajs/progress#11]
The nprogress library allows you to configure a parent container like so:

```javascript
NProgress.configure({ parent: '#container' });
```
Is it possible to add this configuration option?

**Comment by reinink** [comment]
So, for it's worth, you could be able to just call `NProgress.configure()` to do this, since it's a singleton.

That said, this isn't currently possible with this library, but if you want to submit a PR to add it, I'd certainly consider it. 👍

**Comment by crispincornett** [comment]
Ah okay, just confirming that it works to set the NProgress.configure option.

@reinink thanks for your time on Inertia, I'm really enjoying it!
