### ISSUE TITLE
Progress bar doesn't run as expected

### ISSUE THREAD

**Issue by satyakresna** [inertiajs/progress#13]
Hi @reinink, I use inertia/progress in my [Laravel Inertia Svelte Demo](https://github.com/satyakresna/inertia-svelte). But, when I move from first menu to another menu (Home,  About, Contact) using mouse click I expect that progress indicator run but it doesn't.

I already setup the inertia progress based on [inertiajs documentation](https://inertiajs.com/progress-indicators).

1. Install `npm install @inertiajs/progress`
2. Initialize inertia progress in [app.js](https://github.com/satyakresna/inertia-svelte/blob/main/resources/js/app.js). Here's the code.

```js
import { App } from '@inertiajs/inertia-svelte';
import { InertiaProgress } from '@inertiajs/progress';

InertiaProgress.init();

const el = document.getElementById('app');

new App({
    target: el,
    props: {
        initialPage: JSON.parse(el.dataset.page),
        resolveComponent: name => import(`./Pages/${name}.svelte`)
    }
});
```

I'm using:
- `@inertiajs/inertia`: ^0.7.0
- `@inertia/inertia-svelte`: ^0.5.2
-  `@inertia/progress`: ^0.2.3

Screen record attach below.

https://user-images.githubusercontent.com/11099186/102701269-41b46f80-4290-11eb-8a75-3f774b316004.mov

Is there any step that I'm missing?

Thanks.

**Comment by reinink** [comment]
The progress bar is only shown after `250ms`. Meaning locally you will not see it, unless you throttle your connection, or force a delay in your server-side code.

You can customize this delay in the progress bar settings:

```js
InertiaProgress.init({
  // The delay after which the progress bar will
  // appear during navigation, in milliseconds.
  delay: 250,
})
```

**Comment by satyakresna** [comment]
Thanks @reinink.
