### ISSUE TITLE
Adjusing bar line width

### ISSUE THREAD

**Issue by danialwafiy** [inertiajs/progress#15]
Is there a simple way to adjust the lineWidth of the bar? Im trying to make it thicker.

    InertiaProgress.init({
      delay: 0,
      color: '#6875F5',
      includeCSS: true,
      showSpinner: false,
    })

the docs didnt mentioned about the width;

**Comment by reinink** [comment]
We use the [nprogress](https://github.com/rstacruz/nprogress) library under the hood, and I don't think that's an option with that library. I'd recommend just adding some custom CSS to make the line thicker. 👍
