### ISSUE TITLE
event not getting to start method

### ISSUE THREAD

**Issue by flowdau** [inertiajs/progress#4]
I am using current versions of Laravel & Inertia.js. I am also using IntertiaProgress 01.2 and looking to use it during a file upload with axios

The files all upload OK but the console shows:

`
app.js:33316 Uncaught (in promise) TypeError: Cannot read property 'defaultPrevented' of undefined
`

Tracing this back it points to here in the source of InertiaProgress:

 ```
start(event) {
    Promise.resolve().then(() => {
      if (event.defaultPrevented) {
        return
      }

      this.inProgress++
      clearTimeout(this.timeout)
      this.timeout = setTimeout(() => {
        Nprogress.set(0)
        Nprogress.start()
      }, this.delay)
    })
  },
```

If I console.log(event) I get undefined.

My upload() method:

```
upload(files) {
    let url = this.$route('library.upload');
    this.$root.showLoading = true;

    const uploadConfig = {
        timeout: 10000,
        onUploadProgress: function(progressEvent) {
            let percentCompleted = Math.round((progressEvent.loaded * 100) / progressEvent.total)
            InertiaProgress.progress(percentCompleted)
        }
    }

    InertiaProgress.start()

    axios.post(url, {
        files,
    },
        uploadConfig
    ).then(res => {
        let files = res.data.files
        if (files.length) {
            this.filesList = cloneDeep(files)
        }

        this.newFiles = []

        InertiaProgress.finish()
        this.$root.showLoading = false
    }).catch(err => {
        console.log(err)

        InertiaProgress.finish()
        this.$root.showLoading = false
    })

```
Did I miss something or is this an issue with the current version? Thanks.

PS: great work with Inertia.Js!

**Comment by Priet** [comment]
I've run into the same issue when you try to manually show the progress bar.

See line 109 in progress.js:

`      if (event.defaultPrevented) {`

If you call it as `InertiaProgress.start({})` it won't trigger an error. However, I've found that `InertiaProgress.finish()` doesn't hide the progress bar.

**Comment by reinink** [comment]
So if you want to manually trigger the progress bar, I'd recommend just using [nprogress](https://ricostacruz.com/nprogress/) directly, and not use this library.

The `start`, `progress`, and `finish` methods in this library are considered private, and are not meant to be called directly.

**Comment by maggz69** [comment]
> 
> 
> So if you want to manually trigger the progress bar, I'd recommend just using [nprogress](https://ricostacruz.com/nprogress/) directly, and not use this library.
> 
> The `start`, `progress`, and `finish` methods in this library are considered private, and are not meant to be called directly.

Post installing this library, how then will the progress indicators gets called? Is it via inertiajs when clicking the inertia-link or are we meant to add some more code?

**Comment by reinink** [comment]
@maggz69 When you call `InertiaProgress.init()`, this library automatically registers event listeners for events that Inertia fires off when starting a visit, stopping a visit, and during file upload progress. This library uses that to display the loading bar.

Meaning, you need to do nothing...it's all handled for you. 👍

**Comment by maggz69** [comment]
Thanks for this. I'm currently trying to troubleshoot this on my app because I have enabled the progress bar and whenever I click on the inertia-href, I can see the dom update the body with the nprogress class. I however don't see the progress bar on the page.

I haven't done anything fancy with intstalling the progress par, not event the config. Any advise on what the issue could be?

**Comment by reinink** [comment]
@maggz69 What version of `inertiajs/inertia` are you on?
