### ISSUE TITLE
Uncaught TypeError: Cannot read property 'visit' of null

### ISSUE THREAD

**Issue by micakin** [inertiajs/progress#6]
Got this error, i'm trying to use for laravel Jetstream project with Inertiajs

Uncaught TypeError: Cannot read property 'visit' of null
    at HTMLDocument.s (app.js:122)
    at Object.fireEvent (app.js:109)
    at app.js:109
    at <anonymous>

**Comment by bbeng89** [comment]
I'm getting this error as well. I did the init inside my app.js, which looks like this:

```js
require('./bootstrap');

import Vue from 'vue';

import { InertiaApp } from '@inertiajs/inertia-vue';
import { InertiaForm } from 'laravel-jetstream';
import { InertiaProgress } from '@inertiajs/progress';
import PortalVue from 'portal-vue';

Vue.mixin({ methods: { route } });
Vue.use(InertiaApp);
Vue.use(InertiaForm);
Vue.use(PortalVue);

InertiaProgress.init();

const app = document.getElementById('app');

new Vue({
    render: (h) =>
        h(InertiaApp, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                resolveComponent: (name) => require(`./Pages/${name}`).default,
            },
        }),
}).$mount(app);
```

Is this not the right place to init?

**Comment by reinink** [comment]
Hmm, this is almost guaranteed to be a result of using `@inertiajs/progress@v0.2.0`, which [requires a newer version](https://github.com/inertiajs/progress/releases/tag/0.2.0) of Inertia.js. I'd recommend either upgrading Inertia.js to the latest version, or downgrading `@inertiajs/progress` to `^0.1.0`.

Please report back if that helps. 👍

**Comment by bbeng89** [comment]
Ahh, that did the trick. Updated the following:

`@inertiajs/inertia` from `^0.3.0` to `^0.6.1`
`@inertiajs/inertia-vue` from `^0.2.0` to `^0.4.1`
(`@inertiajs/progress` was already at `^0.2.1`)

 For anyone else coming from a fresh install of Jetstream, updating inertia required some changes... the main one being anywhere that accessed shared data like `$page.user` or `$page.jetstream` has to be changed to `$page.props.user` and `$page.props.jetstream`. Not sure if this is documented anywhere...

**Comment by reinink** [comment]
Awesome, thanks for reporting back @bbeng89. That's what I expected. 👍 

And yes, the `$page.props` change was documented. See [here](https://github.com/inertiajs/inertia/releases/tag/inertia-vue%40v0.3.0).

**Comment by naimurhasan** [comment]
Thanks the problem has been solved quickly in jetstream with

npm uninstall @inertiajs/progress
npm i @inertiajs/progress@0.1.0
